Fix banned function detection to handle functions with special characters and improve error reporting

diff --git a/.github/workflows/banned_function.yml b/.github/workflows/banned_function.yml
--- a/.github/workflows/banned_function.yml
+++ b/.github/workflows/banned_function.yml
@@ -31,8 +31,9 @@ jobs:
           if [ -n "$banned_functions" ]; then
             while IFS= read -r function; do
               if [ -n "$allowed_functions" ]; then
-                if ! echo "$allowed_functions" | grep -qw "$function"; then
-                  echo "::error file=./binary::Banned function detected: $function"
+                function=$(`echo $function | sed 's/@/\n/g'`)
+                if ! echo "$allowed_functions" | grep -qw "$function[0]"; then
+                  echo "::error file=./binary::Banned function detected: $function[0]"
                 fi
               else
                 echo "::error file=./binary::Banned function detected: $function"
