Update chocolatine.yml

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -47,90 +47,90 @@ jobs:
           fi
 
   check_program_compilation:
-      name: Compilation checker
-      id: check_program_compilation
-      # needs: check_coding_style
-      runs-on: ubuntu-latest
-      container: epitechcontent/epitest-docker
+    name: Compilation checker
+    id: check_program_compilation
+    needs: check_coding_style
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
 
-      steps:
-        - name: Check make "all" rule
-          timeout-minutes: 2
-          run: make
+    steps:
+      - name: Check make "all" rule
+        timeout-minutes: 2
+        run: make
 
-        - name: Try to clean
-          run: make clean
+      - name: Try to clean
+        run: make clean
 
-        - name: Check if the binary stay here
-          run: |
-            SHOULD_EXIT=0
+      - name: Check if the binary stay here
+        run: |
+          SHOULD_EXIT=0
 
-            for FILE in $EXECUTABLES; do
-                if [[ -s $FILE ]]; then
-                    if [[ $(test -f $FILE) ]]; then
-                        echo "::notice $FILE has been found and is executable"
-                    else
-                        echo "::error $FILE has been found but is not executable"
-                        SHOULD_EXIT=1
-                    fi
-                else
-                    echo "::error title=Executable not found,file=${FILE}::Please ensure your file has been compile"
-                    SHOULD_EXIT=1
-                fi
-            done
-            if [[ $SHOULD_EXIT == 1 ]]; then
-                exit 1
-            fi
+          for FILE in $EXECUTABLES; do
+              if [[ -s $FILE ]]; then
+                  if [[ $(test -f $FILE) ]]; then
+                      echo "::notice $FILE has been found and is executable"
+                  else
+                      echo "::error $FILE has been found but is not executable"
+                      SHOULD_EXIT=1
+                  fi
+              else
+                  echo "::error title=Executable not found,file=${FILE}::Please ensure your file has been compile"
+                  SHOULD_EXIT=1
+              fi
+          done
+          if [[ $SHOULD_EXIT == 1 ]]; then
+              exit 1
+          fi
 
   run_tests:
-      name: Run criterion test
-      id: run_tests
-      needs: check_program_compilation
-      runs-on: ubuntu-latest
-      container: epitechcontent/epitest-content
+    name: Run criterion test
+    id: run_tests
+    needs: check_program_compilation
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-content
 
-      steps:
-        - name: Run make test
-          timeout-minutes: 2
-          run: make tests_run
+    steps:
+      - name: Run make test
+        timeout-minutes: 2
+        run: make tests_run
 
   push_to_mirror:
-      name: Push to a mirror repository
-      if: ${{ github.event_name == 'push' }}
-      needs: run_tests
-      runs-on: ubuntu-latest
+    name: Push to a mirror repository
+    if: ${{ github.event_name == 'push' }}
+    needs: run_tests
+    runs-on: ubuntu-latest
 
-      steps:
-        - name: Checkout
-          uses: actions/checkout@v4
-          with:
-            fetch-depth: 0
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-        - name: Create SSH Key
-          run: |
-            mkdir -p ~/.ssh
-            echo "${{ env.SSH_KEY }}" > ~/.ssh/id_rsa
-            chmod 600 ~/.ssh/id_rsa
-            ssh-keyscan -t rsa $(echo ${{ env.MIRROR_URL }} | cut -d':' -f1 | cut -d'@' -f2) >> ~/.ssh/known_hosts
-          env:
-            SSH_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+      - name: Create SSH Key
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ env.SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan -t rsa $(echo ${{ env.MIRROR_URL }} | cut -d':' -f1 | cut -d'@' -f2) >> ~/.ssh/known_hosts
+        env:
+          SSH_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
 
-        - name: Remove .github directory
-          run: |
-            git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch .github' --prune-empty --tag-name-filter cat -- --all
-            git gc --prune=now
-            git clean -fd
+      - name: Remove .github directory
+        run: |
+          git filter-branch --force --index-filter 'git rm -r --cached --ignore-unmatch .github' --prune-empty --tag-name-filter cat -- --all
+          git gc --prune=now
+          git clean -fd
 
-        - name: Verify Repository
-          run: |
-            git fsck --full || echo "Git fsck completed with warnings"
-            git gc || echo "Git gc completed with warnings"
+      - name: Verify Repository
+        run: |
+          git fsck --full || echo "Git fsck completed with warnings"
+          git gc || echo "Git gc completed with warnings"
 
-        - name: Push to mirror
-          run: |
-            git remote add -f mirror ${{ env.MIRROR_URL }}
-            git push mirror --mirror --prune --force
-            echo "Successfully mirrored to ${{ env.MIRROR_URL }} "
+      - name: Push to mirror
+        run: |
+          git remote add -f mirror ${{ env.MIRROR_URL }}
+          git push mirror --mirror --prune --force
+          echo "Successfully mirrored to ${{ env.MIRROR_URL }} "
 
   banned-function:
     id: banned_function
