Update chocolatine.yml

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -12,42 +12,42 @@ env:
 
 jobs:
   check_coding_style:
-    - name: Coding Style Checking
-      id: check_coding_style
-      runs-on: ubuntu-latest
-      container: ghcr.io/epitech/coding-style-checker:latest
+    name: Coding Style Checking
+    id: check_coding_style
+    runs-on: ubuntu-latest
+    container: ghcr.io/epitech/coding-style-checker:latest
 
-      steps:
-        - name: Checkout the code
-          uses: actions/checkout@v4
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v4
 
-        - name: Process coding style
-          shell: bash
-          # It's funny, it's not coding style
-          run: |
-            check.sh $(pwd) $(pwd)
-            should_exit=0
-            if [ -s "$(pwd)/coding-style-reports.log" ]; then
-              while IFS= read -r ERROR
-                do
-                  array=(`echo $ERROR | sed 's/:/\n/g'`)
+      - name: Process coding style
+        shell: bash
+        # It's funny, it's not coding style
+        run: |
+          check.sh $(pwd) $(pwd)
+          should_exit=0
+          if [ -s "$(pwd)/coding-style-reports.log" ]; then
+            while IFS= read -r ERROR
+              do
+                array=(`echo $ERROR | sed 's/:/\n/g'`)
 
-                  if [ "${array[2]}" != "INFO" ]; then
-                    should_exit=1
-                    echo "::error title=${array[2]},file=${array[0]#./},line=${array[1]}::${array[3]}"
-                  else
-                    echo "::warning title=${array[2]},file=${array[0]#./},line=${array[1]}::${array[3]}"
-                  fi
-              done < "$(pwd)/coding-style-reports.log"
-              if [ "$should_exit" == 1 ]; then
-                exit 1
-              fi
-            else
-              echo "::notice ::No coding style errors detected ! Great Job"
+                if [ "${array[2]}" != "INFO" ]; then
+                  should_exit=1
+                  echo "::error title=${array[2]},file=${array[0]#./},line=${array[1]}::${array[3]}"
+                else
+                  echo "::warning title=${array[2]},file=${array[0]#./},line=${array[1]}::${array[3]}"
+                fi
+            done < "$(pwd)/coding-style-reports.log"
+            if [ "$should_exit" == 1 ]; then
+              exit 1
             fi
+          else
+            echo "::notice ::No coding style errors detected ! Great Job"
+          fi
 
   check_program_compilation:
-    - name: Compilation checker
+      name: Compilation checker
       id: check_program_compilation
       needs: check_coding_style
       runs-on: ubuntu-latest
@@ -83,7 +83,7 @@ jobs:
             fi
 
   run_tests:
-    - name: Run criterion test
+      name: Run criterion test
       id: run_tests
       needs: check_program_compilation
       runs-on: ubuntu-latest
@@ -95,7 +95,7 @@ jobs:
           run: make tests_run
 
   push_to_mirror:
-    - name: Push to a mirror repository
+      name: Push to a mirror repository
       if: ${{ github.event_name == 'push' }}
       needs: run_tests
       runs-on: ubuntu-latest
@@ -133,52 +133,52 @@ jobs:
             echo "Successfully mirrored to ${{ env.MIRROR_URL }} "
 
   banned-function:
-    - id: banned_function
-      needs: run_tests
-      runs-on: ubuntu-latest
+    id: banned_function
+    needs: run_tests
+    runs-on: ubuntu-latest
 
-      steps:
-        - name: Checkout the code
-          uses: actions/checkout@v4xz
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v4xz
 
-        - name: Install dependencies
-          run: sudo apt update && sudo apt install -y cmake make gcc clang
+      - name: Install dependencies
+        run: sudo apt update && sudo apt install -y cmake make gcc clang
 
-        - name: Create binary
-          run: make
+      - name: Create binary
+        run: make
 
-        - name: Check for banned functions
-          shell: bash
-          run: |
-            if [ -f allowed_function.note ]; then
-              allowed_functions=$(cat allowed_function.note)
-            else
-              allowed_functions=""
-              echo "::warning ::Warning: allowed_function.note not found."
-            fi
-            echo $(ls)
-            should_exit=0
-            banned_functions=$(nm -u ${{ env.BINARY_NAME }} | grep GLIBC | grep -v "__" || true)
-            if [ -n "$banned_functions" ]; then
-                IFS=$'\n'
-                for function in ${banned_functions}
-                  do
-                    function_name=$(echo "$function" | sed -E 's/^[[:space:]]*[^[:space:]]+[[:space:]]+([a-zA-Z0-9_]+)(@.*)?$/\1/')
-                    if [ -n "$allowed_functions" ]; then
-                        if [[ ! $(echo "$allowed_functions" | grep -F "$function_name") ]]; then
-                            should_exit=1
-                            echo "::error file=./binary::Banned function detected: $function_name"
-                        fi
-                    else
-                        echo "::error file=./binary::Banned function detected: $function_name"
-                        should_exit=1
-                    fi
-                done
-                if [ "$should_exit" == 1 ]; then
-                  exit 1
-                else
-                  echo "::notice ::No banned functions found."
-                fi
-            else
-              echo "::notice ::No banned functions found."
-            fi
+      - name: Check for banned functions
+        shell: bash
+        run: |
+          if [ -f allowed_function.note ]; then
+            allowed_functions=$(cat allowed_function.note)
+          else
+            allowed_functions=""
+            echo "::warning ::Warning: allowed_function.note not found."
+          fi
+          echo $(ls)
+          should_exit=0
+          banned_functions=$(nm -u ${{ env.BINARY_NAME }} | grep GLIBC | grep -v "__" || true)
+          if [ -n "$banned_functions" ]; then
+              IFS=$'\n'
+              for function in ${banned_functions}
+                do
+                  function_name=$(echo "$function" | sed -E 's/^[[:space:]]*[^[:space:]]+[[:space:]]+([a-zA-Z0-9_]+)(@.*)?$/\1/')
+                  if [ -n "$allowed_functions" ]; then
+                      if [[ ! $(echo "$allowed_functions" | grep -F "$function_name") ]]; then
+                          should_exit=1
+                          echo "::error file=./binary::Banned function detected: $function_name"
+                      fi
+                  else
+                      echo "::error file=./binary::Banned function detected: $function_name"
+                      should_exit=1
+                  fi
+              done
+              if [ "$should_exit" == 1 ]; then
+                exit 1
+              else
+                echo "::notice ::No banned functions found."
+              fi
+          else
+            echo "::notice ::No banned functions found."
+          fi
