Fix syntax in coding style checker workflow for error handling

diff --git a/.github/workflows/coding-style.yml b/.github/workflows/coding-style.yml
--- a/.github/workflows/coding-style.yml
+++ b/.github/workflows/coding-style.yml
@@ -20,13 +20,12 @@ jobs:
             check.sh $(pwd) $(pwd)
             CSERR=$(cat $(pwd)/coding-style-reports.log)
             for ERR in $CSERR; do
-                str=(`echo $ERR | sed 's/:/\n/g'`)
-                echo "::error file=${str[1]#./},title=${str[3]#./} coding style errors detected: ${str[2]#./}::${str[4]#./}"
+              str=(`echo $ERR | sed 's/:/\n/g'`)
+              echo "::error file=${str[1]#./},title=${str[3]#./} coding style errors detected: ${str[2]#./}::${str[4]#./}"
             done
-            if [[ -n $CS ]]
-            then
-                exit 1
+            if [[ -n $CS ]] then
+              exit 1
             else
-                echo No coding style errors detected
+              echo No coding style errors detected
             fi
     
