Refactor coding style checker workflow for improved error handling and readability

diff --git a/.github/workflows/coding-style.yml b/.github/workflows/coding-style.yml
--- a/.github/workflows/coding-style.yml
+++ b/.github/workflows/coding-style.yml
@@ -7,25 +7,24 @@ on:
   pull_request:
 
 jobs:
-    checker:
-      runs-on: ubuntu-latest
-      container: ghcr.io/epitech/coding-style-checker:latest
+  checker:
+    runs-on: ubuntu-latest
+    container: ghcr.io/epitech/coding-style-checker:latest
 
-      steps:
-        - name: Checkout the code
-          uses: actions/checkout@v4
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v4
         
-        - name: Run checker
-          run: |
-            check.sh $(pwd) $(pwd)
-            CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
-            for ERRORS in $CODING_STYLE_ERRORS; do
-              array=(`echo $ERRORS | sed 's/:/\n/g'`)
-              echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
-            done
-            if [[ -n $CODING_STYLE_ERRORS ]]
-            then
-              exit 1
-            else
-              echo No coding style errors detected
-            fi
+      - name: Run checker
+        run: |
+          check.sh $(pwd) $(pwd)
+          CSERR=$(cat $(pwd)/coding-style-reports.log)
+          if [[ -n "$CSERR" ]]; then
+            while IFS= read -r ERR; do
+              str=($(echo $ERR | sed 's/:/\n/g'))
+              echo "::error file=${str[1]#./},title=${str[3]#./} coding style errors detected: ${str[2]#./}::${str[4]#./}"
+            done <<< "$CSERR"
+            exit 1
+          else
+            echo "No coding style errors detected"
+          fi
