Refactor coding style checker workflow for improved readability and structure

diff --git a/.github/workflows/coding-style.yml b/.github/workflows/coding-style.yml
--- a/.github/workflows/coding-style.yml
+++ b/.github/workflows/coding-style.yml
@@ -17,16 +17,14 @@ jobs:
         
       - name: Run checker
         run: |
-          bash -c "
-            check.sh $(pwd) $(pwd)
-            CSERR=$(cat $(pwd)/coding-style-reports.log)
-            if [[ -n \"$CSERR\" ]]; then
-              while IFS= read -r ERR; do
-                str=($(echo \$ERR | sed 's/:/\\n/g'))
-                echo \"::error file=${str[1]#./},title=${str[3]#./} coding style errors detected: ${str[2]#./}::${str[4]#./}\"
-              done <<< \"\$CSERR\"
-              exit 1
-            else
-              echo \"No coding style errors detected\"
-            fi
-          "
+          check.sh $(pwd) $(pwd)
+          CSERR=$(cat $(pwd)/coding-style-reports.log)
+          if [[ -n \"$CSERR\" ]]; then
+            while IFS= read -r ERR; do
+              str=($(echo \$ERR | sed 's/:/\\n/g'))
+              echo \"::error file=${str[1]#./},title=${str[3]#./} coding style errors detected: ${str[2]#./}::${str[4]#./}\"
+            done <<< \"\$CSERR\"
+            exit 1
+          else
+            echo \"No coding style errors detected\"
+          fi
